// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIWtXQHxz6NtpgWSwzfuHoolGfrOTOOIU',
    appId: '1:698398921018:web:fc0c8b1e867a542d994003',
    messagingSenderId: '698398921018',
    projectId: 'asol-game',
    authDomain: 'asol-game.firebaseapp.com',
    databaseURL: 'https://asol-game-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'asol-game.firebasestorage.app',
    measurementId: 'G-E3B3G2X57Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgWTqvG2lBRnPCGKqd3K6yKdGpGlGUQIc',
    appId: '1:698398921018:android:8e374218aee57484994003',
    messagingSenderId: '698398921018',
    projectId: 'asol-game',
    databaseURL: 'https://asol-game-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'asol-game.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUEGVPBqh0JTPKAWItQymPdo33RgoUZ3E',
    appId: '1:698398921018:ios:9df2ea35bac9be04994003',
    messagingSenderId: '698398921018',
    projectId: 'asol-game',
    databaseURL: 'https://asol-game-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'asol-game.firebasestorage.app',
    iosBundleId: 'com.example.bidaGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUEGVPBqh0JTPKAWItQymPdo33RgoUZ3E',
    appId: '1:698398921018:ios:9df2ea35bac9be04994003',
    messagingSenderId: '698398921018',
    projectId: 'asol-game',
    databaseURL: 'https://asol-game-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'asol-game.firebasestorage.app',
    iosBundleId: 'com.example.bidaGame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIWtXQHxz6NtpgWSwzfuHoolGfrOTOOIU',
    appId: '1:698398921018:web:7148077a9230d8f3994003',
    messagingSenderId: '698398921018',
    projectId: 'asol-game',
    authDomain: 'asol-game.firebaseapp.com',
    databaseURL: 'https://asol-game-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'asol-game.firebasestorage.app',
    measurementId: 'G-2Z3NGLR2HX',
  );
}
